import MyProfilePage from '@/pages/MyPage/MyProfilePage';
import React from 'react';

export const lazyRoutes = {
  SocialLoginCallbackPage: React.lazy(() => import('../pages/callback/SocialLoginCallback')),
  MainPage: React.lazy(() => import('../pages/MainPage/NewMainPage')),
  HomePage: React.lazy(() => import('../pages/HomePage/HomePage')),
  MyInfoPage: React.lazy(() => import('../pages/MyPage/MyInfoPage')),
  MyAccountPage: React.lazy(() => import('../pages/MyPage/MyAccountPage')),
  MyMessagePage: React.lazy(() => import('../pages/MyPage/MyMessagePage')),
  MyMessageDetailPage: React.lazy(() => import('../pages/MyPage/MyMessageDetailPage')),
  MyPage: React.lazy(() => import('../pages/MyPage/MyPage')),
  MyPayPage: React.lazy(() => import('../pages/MyPage/MyPayPage')),
  MyPaymentHistory: React.lazy(() => import('../pages/MyPage/MyPaymentHistoryPage')),
  MyPromptPage: React.lazy(() => import('../pages/MyPage/MyPromptPage')),
  MyReviewPage: React.lazy(() => import('../pages/MyPage/MyReviewPage')),
  MyProfilePage: React.lazy(() => import('../pages/MyPage/MyProfilePage')),
  NotFoundPage: React.lazy(() => import('../pages/NotFoundPage/NotFoundPage')),
  ProfilePage: React.lazy(() => import('../pages/ProfilePage/NewProfilePage')),
  PromptCreatePage: React.lazy(() => import('../pages/PromptCreatePage/PromptCreatePage')),
  PromptLandingPage: React.lazy(() => import('../pages/PromptCreatePage/PromptLandingPage')),
  PromptCreateTextPage: React.lazy(() => import('../pages/PromptCreatePage/PromptCreateTextPage')),
  PromptCreateImgPage: React.lazy(() => import('../pages/PromptCreatePage/PromptCreateImgPage')),
  PromptDetailPage: React.lazy(() => import('../pages/PromptDetailPage/PromptDetailPage')),
  PromptGuidePage: React.lazy(() => import('../pages/PromptGuidePage/PromptGuidePage')),
  PromptNoticePage: React.lazy(() => import('../pages/PromptGuidePage/PromptNoticePage')),
  PromptTipePage: React.lazy(() => import('../pages/PromptGuidePage/PromptTipPage')),
  PromptGuideDetailPage: React.lazy(() => import('../pages/PromptGuidePage/PromptGuideDetailPage')),
  PromptEditPage: React.lazy(() => import('../pages/PromptEdit/PromptEditPage')),
  AdminComplaintPage: React.lazy(() => import('../pages/AdminPage/AdiminComplaintPage')),
  PromptGuideCreatePage: React.lazy(() => import('../pages/AdminPage/PromptGuideCreatePage')),
  AdminComplaintDetailPage: React.lazy(() => import('../pages/AdminPage/AdminComplaintDetailPage')),
};
