import type { Prompt, Creator } from "@/types/prompt";

export const dummyPrompts: Prompt[] = [
  {
    id: 1,
    authorName: "홍길동",
    authorImg: null,
    model: "ChatGPT",
    tags: ["책요약", "자산계획서", "프로토타입", "IT"],
    title: "IT사업계획서 작성 프롬프트",
    price: 2200,
    rating: 5,
    views: 2109,
    likes: 120,
    content: "사업 개요 \n사업명: (쇼핑몰 이름) \n형태: 온라인 쇼핑몰 \n주요 상품: 20대 여성을 타겟으로 한 다양한 스타일의 원피스 \n목표 시장: 국내 온라인 패션 시장, 20대 여성 고객 \n판매 채널: 자체 웹사이트, 인스타그램, 네이버 스마트스토어, 무신사, 지그재그 등 \n운영 방식: 자체 제작 및 도매 구매 혼합 운영...\nddd\nddd",
    downloadCount: 120,
  },
  {
    id: 2,
    authorName: "디자인킹",
    authorImg: null,
    model: "Midjourney",
    tags: ["추상화", "수묵화", "레디자인", "무드레퍼런스"],
    title: "동양풍 일러스트 이미지 생성",
    price: 1800,
    rating: 4,
    views: 1145,
    likes: 98,
    content: "- 동양 여성 캐릭터 일러스트 세트\n- 4:5 비율 세로 이미지...",
    downloadCount: 198,
  },
  {
    id: 3,
    authorName: "정문장",
    authorImg: null,
    model: "ChatGPT",
    tags: ["글쓰기", "자기계발", "GPT", "습관"],
    title: "하루 15분 글쓰기 훈련 프롬프트",
    price: 5000,
    rating: 4.5,
    views: 890,
    likes: 76,
    content: "창작 글쓰기 실력을 키우고 싶은 사람들을 위한 짧고 강력한 GPT 글쓰기 훈련 시리즈. 매일 다른 주제를 제공합니다.",
    downloadCount: 102,
  },
  {
    id: 4,
    authorName: "한개발",
    authorImg: null,
    model: "GPT-4",
    tags: ["프론트엔드", "면접", "시뮬레이션", "코딩"],
    title: "프론트엔드 면접 시뮬레이터",
    price: 15000,
    rating: 4.8,
    views: 1320,
    likes: 134,
    content: "React, TypeScript, HTML/CSS 등 프론트엔드 개발자 면접 대비를 위한 실전 QA 시뮬레이션 프롬프트입니다.",
    downloadCount: 215,
  },
  {
    id: 5,
    authorName: "박사랑",
    authorImg: null,
    model: "ChatGPT",
    tags: ["연애", "조언", "감정", "상담"],
    title: "GPT 연애 상담 프롬프트",
    price: 0,
    rating: 4.2,
    views: 2300,
    likes: 210,
    content: "연인과의 갈등, 썸 고민, 고백 타이밍 등 연애 관련 고민을 GPT가 상황에 맞춰 친절히 조언해주는 프롬프트입니다.",
    downloadCount: 503,
  }
];

export const dummyCreators: Creator[] = [
  { id: 1, name: "주토피아노", avatar: null, followers: 1092, followed: false },
  { id: 2, name: "이해인", avatar: null, followers: 120, followed: false },
  { id: 3, name: "폴로", avatar: null, followers: 222, followed: true },
  { id: 4, name: "올랄라", avatar: null, followers: 90, followed: true },
  { id: 5, name: "안민수", avatar: null, followers: 23, followed: false },
  { id: 6, name: "뽀또", avatar: null, followers: 42, followed: true },
];
