import type { Prompt, Creator } from '@/types/prompt';

export const dummyPrompts: Prompt[] = [
  {
    author_id: 1,
    authorname: '주토피아노',
    authorimage: null,
    prompt_id: 1,
    title: 'IT사업계획서 작성 프롬프트',
    description:
      '사업 개요 \n사업명: (쇼핑몰 이름) \n형태: 온라인 쇼핑몰 \n주요 상품: 20대 여성을 타겟으로 한 다양한 스타일의 원피스 \n목표 시장: 국내 온라인 패션 시장, 20대 여성 고객 \n판매 채널: 자체 웹사이트, 인스타그램, 네이버 스마트스토어, 무신사, 지그재그 등 \n운영 방식: 자체 제작 및 도매 구매 혼합 운영...\nddd\nddd\nd\nd\nd\nd\nd\nd',
    has_image: false,
    is_free: false,
    model: 'GPT-4',
    price: 5000,
    downloadCount: 150,
    views: 2109,
    likes: 120,
    rating_avg: 5,
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
    images: [],
    tags: ['책요약', '자산계획서', '프로토타입', 'IT'],
    keyword: '사업계획서',
  },
  {
    author_id: 2,
    prompt_id: 2,
    authorimage: null,
    authorname: '홍길동',
    title: '동양풍 일러스트 이미지 생성',
    description: '- 동양 여성 캐릭터 일러스트 세트\n- 4:5 비율 세로 이미지...',
    has_image: false,
    is_free: false,
    model: 'midjourney',
    price: 2500,
    downloadCount: 200,
    views: 1145,
    likes: 98,
    rating_avg: 4,
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
    images: [],
    tags: ['추상화', '수묵화', '레디자인', '무드레퍼런스'],
    keyword: '일러스트',
  },
  {
    author_id: 3,
    prompt_id: 3,
    authorname: '디자인킹',
    authorimage: null,
    title: '하루 15분 글쓰기 훈련 프롬프트',
    description:
      '창작 글쓰기 실력을 키우고 싶은 사람들을 위한 짧고 강력한 GPT 글쓰기 훈련 시리즈. 매일 다른 주제를 제공합니다.',
    has_image: false,
    is_free: false,
    model: 'ChatGPT',
    price: 3300,
    downloadCount: 75,
    views: 890,
    likes: 76,
    rating_avg: 4.5,
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
    images: [],
    tags: ['글쓰기', '자기계발', 'GPT', '습관'],
    keyword: '글쓰기',
  },
  {
    author_id: 4,
    prompt_id: 4,
    authorname: '코딩마스터',
    authorimage: null,
    title: '프론트엔드 면접 시뮬레이터',
    description: 'React, TypeScript, HTML/CSS 등 프론트엔드 개발자 면접 대비를 위한 실전 QA 시뮬레이션 프롬프트입니다.',
    has_image: false,
    is_free: false,
    model: 'Gemini',
    price: 15000,
    downloadCount: 50,
    views: 1320,
    likes: 134,
    rating_avg: 4.8,
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
    images: [],
    tags: ['프론트엔드', '면접', '시뮬레이션', '코딩'],
    keyword: '면접',
  },
  {
    author_id: 5,
    prompt_id: 5,
    title: 'GPT 연애 상담 프롬프트',
    authorname: '연애상담사',
    authorimage: null,
    description:
      '연인과의 갈등, 썸 고민, 고백 타이밍 등 연애 관련 고민을 GPT가 상황에 맞춰 친절히 조언해주는 프롬프트입니다.',
    has_image: false,
    is_free: true,
    model: 'Midjourney',
    price: 1800,
    downloadCount: 120,
    views: 2300,
    likes: 210,
    rating_avg: 4.2,
    created_at: '2025-01-01T00:00:00.000Z',
    updated_at: '2025-01-02T00:00:00.000Z',
    images: [],
    tags: ['연애', '조언', '감정', '상담'],
    keyword: '연애',
  },
];

export const dummyCreators: Creator[] = [
  { id: 1, name: '주토피아노', avatar: null, followers: 1092, followed: false },
  { id: 2, name: '이해인', avatar: null, followers: 120, followed: false },
  { id: 3, name: '폴로', avatar: null, followers: 222, followed: true },
  { id: 4, name: '올랄라', avatar: null, followers: 90, followed: true },
  { id: 5, name: '안민수', avatar: null, followers: 23, followed: false },
  { id: 6, name: '뽀또', avatar: null, followers: 42, followed: true },
];
